language: node_js
node_js:
- 12.16.2
before_deploy:
- npm install --prefix src/accounts.web
- npm run build --prefix src/accounts.web
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: Y9ZcV3CJ8Df4788CFdDOZnX0mjz01k3jAPqaMRyNNIrCcwUPDXxKAsuBaLOEvElSDTNxDiNIInRbWaFf1eQr08rWAXv97w8GH2Km2N1wy+OpTJN8JBwGErMcnhC3fqTxnqGTIS+2fmoGk8J5rYSiEF0RlWzc9Eb1aQ/b0YrxjqJsPVvFLU7+rC0wjLqGGd/HUwy+0fgqscgUepswbGyNhSGbdkam7MNhuJxg2TCW3VLcVNFxhQsAFWGTEs1Ro1X9hvnTb1C4lBKybEtVZPqqboOn/uWiQuX4nMcqcyLF33e2OzEkZXRLUaTPta5eNARBDLzWjL+YKhF3JUbrPZoaPjXE2zI+6lyo99p0FJ+FF8flqgXS7XBKZvXV36Bc8i7ULfbUoqDfaZUNRCwfKQ7uF56ZD9fD77LhQST2jElj9CeXiqUw+KIen48I6SxDDfUVXHsbVsLKji5/rJJbCVPRTOT3XfRMInPt74A6WpP93TRQ5G5giTilXHzAk8oGYeRqDUtzCQyRHwBDT9zKcPdHpwC1uhTsLcnoX9c4Us4TtxCsrlDcPq056kVIWi+W7xoiWkoPdu0H4fBhtTbOJcojS4x3zv+YfQuXC4F7HN+mDzbqWrRh2hLDUDRl1s5+Kq4DoyqjrNE4WJL9c6btJnMuM/Hc0VrE4k6vfyX39myXisw=
  app: example-accounts
  on:
    repo: ir-taimal10/example-accounts
  skip_cleanup: 'true'
