language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  email: example.arch.js@gmail.com
  skip_cleanup: true
  api_key:
    secure: J9nKbvNqtIQXxfi8P7WEoPFeN2LhH9Z3OGdpnioZJcbg/IP8P1eh0pY5c0WrKomo0RU43UGVXeSSdxMup2Edb+hd15dEg/6r3HzF8rDJck0UfmxNWd2CSUKdqwfwEsEi5/l2b+G813xT7xlo14+0C8DoShsV4cvSuq/7XWyGY8mnMHC04uJ4bmFYfRSr++SGl2UuuvOOHl0ZD6kq4gWTKKqDioHYdz0bX26rezQXgavpphz2i3OTo6KwqOnKuaCbyDHQtCo3gKYMIyDqP8liizIGiWinNIMymAuLi/ZWeDXFVjrGwKTpuubPv6oFo7EQIArlY93x2yGU8RXHISMukBwJD7nwn1fbmyAkA2zPR58NxGy46ZQgHKZilvL0F5JtsfLaQ+Kix95Th/4/xhnoz0LvYQsz10QZT+FYewsxHHqmD4NWfiDYDfj9Wk2Ey60e2rAOj8Qf0tKp2HzmQpz1kZtRRqiBlPpUGLixVQCvLaPFPkGE0U8u3ICpqabBGE82Z9Ac6woKwHiucfW+0/xGxU0O/Cz/CJB57hCCP2NVYcFFmyyHRDRdv4qwauzpolAzN5o9AxD+hzjd7YxqbjlAk36q5q3HVa1e1thgGtBHMmixFPvpD0gkVKgJRUfjATli2YwXzbGHKxyQtqvrlsjz8gZnkRjEy88LGVRzV0utgAk=
