language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  email: example.arch.js@gmail.com
  skip_cleanup: true
  api_key:
    secure: oz2yvz1e3FeM+OTr0iLZsHHMhQBHvTSHhl0yaN1uyHAYnizrIgB2nbEFrl2lo3JhirLYaS9qxP+kfgIhAoxaX8iqAE3HT2PC2K45USvT2tgOiTt2HlWiEhJ+q0i5uFtsTz9kjl04NEvo4m3P3fEyRrtw/FIL1E5zlptj0QKOAP1HknJR/0Xi+3hU7Niooj3Z5fQMkNRFESA+YTgI3/mGtOF8ImGkBRVbfPnsf/DcSPygRxtiApJnJwy1hcZrP+335Nlp9eFwysp10dXLpY9j7S+z0eVRGrviDmJg7fzrFh4Da5qvwkfR0mD2r+LKpAppcrO/mRYEdz6OrqhGFzDhYILxLwAnan5Pz89MB3gHzdeTAVoUcNkXsOZJRDTckc6lYhZUDTWd2XEXDrCG7ZTHDl2a4oXlodH8gnuu5nj2K4ljVykCHPwj1hmKgs0krYzf1jMiF6Rx/04fcqdX8u5WwhAVBDTD8nbApydOHHev7Rhgai3h1Zqrf6BKOLyMc7AcRQS25c5F754HuS6AqaD0/hshcoamAI3bjnrMbiOq82ETchJ60UITCavsSe/VPAZpJLMRdzqbBpKEtT57OiiJM08VR+OMcZHlwAQWs+5B/sFLK8C46oIu4zzUnrmQ5vek+joXdksUOBp6TysQxFQ3qqgaEpNh1kWMVYXgDaDKdAQ=
  app:
    master: example-accounts
  on:
    repo: ir-taimal10/example-accounts
