language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  email: example.arch.js@gmail.com
  skip_cleanup: true
  api_key:
    secure: r6CrLTmwYvIid5yxu2mFeg7nlv0tDO/fnTw71wZP1jraoVwLPEweFh0b3cFC13Kyg5nXL7VcZhVMM9Z2PkrstQlV557tsoItGCoJlLgz0Hdg0gNjN+J1yfjQF1JAIYAzloXrIGRv6DfZkMyixstkXONZe9QU8qbWPlf39oebCWjMaRLMSQ+vszCNrwLxBqKIxa8Sn3KORG/hv05PKy3ILYWNv+IszW9Xosi67i6HptDAFbMM0aKfpMzdzRMily04PQi/eVTUCrMm0+lkzgjriWjqEDtYZxWvGmMR08SMF5JMILxe9JGaegdUU3IkJ8Mvy35TEX2+XJYvW2NmUpGdib/R4HQ1IuWz/QeRArYH/Xkz7l998caQKn32+ZCQkHWtk+zaduWgru7poB+gvp9x126vBWUxxTvkb2IjrZKVZOBWYhSPHfbqPGRuwDzCkDEIoYnmC1m75fs/os/ullL8dYJWyPIAZAZnEFd1bhFpbO0WNZc7N9UmjOUjtI1c0ZWvv4ghSOHrbGVUKy5IwC+v3Osa/I4pd2j4IY2iTQ3i17U+Gq3SNV0ZHfyPQzbFu7RzezRXYzvkPQ732AWmd6RIE87OprMymap66w5/8f2UdTwoqUvZ+LwoWxff1D7oHrWUK9ER/hUax+grK3jiJMX8HGZn6w/QaPwmtrckmxJVfKc=
  app:
    master: example-accounts
  on:
    repo: ir-taimal10/example-accounts
