language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: TIPCG8eFMkKwVe3vnnyGj79a/MHq+Y+bsitRce07TzVdbjzg1KVvrZ25I2Ffu9DkmM6fY1Cd8dyg90miwjMd/ZJ101bn8AEnnN7wf5f7a0jx2Xv4TEcQYuvXBWsJzBGRB3PrubeZmkDlEBmgY9RRqIpGmVRzoFkCvk3xXDgTAuEMpZiILSN3o/we8MgYU45uVlvvbroxM3bOr5FJMfbQCOioqTKg8rImmRorIZb/Mv62Kmm+kq9UP0mcA56I1hQyWvN2PgkQFCyZEWx+7tV6rWxj3O6tnJuzKVTeZhuDnPiRxZLBQpAOduo89u8rh+9HM5QPbWiLJzPJ4/fCroQpB6Ok1Gvni7qmk4UZn07kRGu9o+vSpR/4bzrf7iy6Kynt/Yt5ZUwDWb1JrPhGIla2j3FV/ZST92dQ/10wmfustcL6D1rDOCEWg7bBuaELg2THJwQsVZkuMMhrNOLstkDsDdIKQG80zdDAJRn+74pvNMKNtlOBfO8r8bxEedgp88W1Yiy/0hVgneH/Bk4Hkhp4Kaj0TrdXsb53j18ixsqxXyDPjeTHUfXBOBya8G8DfOTnZZBi1UcfXyh6uWXLOyY6vy1T64iO/tbTQ+2UOThS4QyqVNasDC3TxpRxlMDVIjVaPUnEXEVkXqgroupmmPA9agRMJ17B/u3G4WPxFNuYrYc=
  app: example-accounts
  on:
    repo: ir-taimal10/example-accounts
  skip_cleanup: 'true'
