language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  email: "example.arch.js@gmail.com"
  skip_cleanup: true
  api_key:
    secure: pzMpeiv27ql4pK06DxC/sPH+mw28c5AxzQX1QJBqO+pVpyc75LnDYrUTiFOl0zrRjBEgA97VFCtCqFilWBnatLWBP3+Fk7vvrA7CQhPeQ0EovdMlGHk701Eg5Dx535mmkc/FiWeW+KYBKhs4xt/ud+OAnnkCcv0Ihr+yB4xnfZsI9X9kOF5X/yiuICAgVoCUJH6RIo0fusjyPWNzzOyGoUHgesUkjW2Y2/gZdYB7ATVOo9b+kmikUwd+N0J3ht992Xihs5c0KqFrx/HrEJb9CEB3UjqE3kOxm2p2ShJ9LM7n+QcdFhG3HkVRQ/g7B/SSmE4R3pwzrpiq3w5zmdbwz7xhaZfCcizj7+xRh1e4ILSafNidhvqFxluFQ5FPKQ5DX6LjnIIUjRDY0e8KMHiY3OaHM9nC+huViguwTSc5diNfkLYdLwxH15h9nBfBLzI8wia3Q3zZV1pE/H6HWi8dVijv2ydpfhuY/GmBo49b57ihcnUpeIJ2gYjkDG5sEVUncDPq7wmJWKPJsP1921h1YgaDOP5GNIuuPLRtyRe0Z+LuMnw11M8Yj99UHMKKMggm4k3M758M449gcwn5vJwf6I/NJL9dsNKQkCh3TrDIFuT1fru9SpajZQ5zuStK/yn4PT+bI2XqM8rVez5p2m5eBSrYjAAF8eV492R8EOtjY1w=
  app:
    master: example-accounts
  on:
    repo: ir-taimal10/example-accounts
