language: node_js
node_js:
- '12.16.2'
before_deploy:
- ng build
deploy:
  provider: heroku
  email: 'rtaimal@gmail.com '
  skip_cleanup: true
  api_key:
    secure: Fes5d+Zk+4bW4IlQ403av+8xIE/dgRfYlJlDgHR0N4BwNacbQdq4Vzqw0dCu2q+yGS28jObgUnqY6Kvj5IgpYPCbsHDIV8gvvcSoitxTPBIr44Wlhzmu6IJ83f2C8YHEgyzwaVnEyAq2nbSpxbC94awARFnBd9D/5AWFPtYPOeiv6G2Ko7abPEGO5VIUZDByZakkvUaNPM8+/Khic5NAGXOttMWaLgbCQJzLp1bGnfY0XOYm4Rr8jJEnkG1bKXW3bPicIqz47Eh7et0QPlMt1h1u38WenXUUey0xV5N0lT+2YTAGbpbi4FNvVcUPIfK0J+mYLPoT6nV0pPTdQ6vmdMVpukBrNV7DhVSi5+7QWv5PfjO/KhZTkN975Y5cGRIC1PoHSxl68rrqv/izTo0dW+ee5O8XmdPX+AqTCFVqLibvtezT5ILd2bcM0uCc+juELwAKSDhsUnrTt7IlYwGYOKnAaEQcyCtfyepoMA7IBgzn8MQasEVOHYOG/q+q17+0CmAGo2R/91taASYJy1ii/s3kHl3DZH6ApCXmXCA6LUWUEYrg7jiIot1mbhF6KRSM0k4WITYXlXUyIYHAygkvm1jr3hI+oiglwWVe5XATs/VlJAtjWgxtQe9BkzI4xwDRu/wfv1YCIbWGT+l+RxJozFNZOi0gQiYwfr3+ban8KE0=
