language: node_js
node_js:
- 12.16.2
before_deploy:
- npm run build
deploy:
  provider: heroku
  email: example.arch.js@gmail.com
  skip_cleanup: true
  api_key:
    secure: fgubDxeGjeTRyiNtMYUG0C+yiaEw8eD1FdyHxSLnqfk2EwZj0VI4IrPRTouaQTKXVXVHKw1MqX/Z48nlerUhtcEY1D6PLliageziQEKbVJogSQaXI1wVbScRwDGtirM/65rOzveCaA3s1IqzT9z63nPVoXWd3LAfXJ/K+0gEwdbLLOlXKe234PzyeJQpedAYuhxhEp5fAjVUKLcLxvrg9+UrQVm9f4qARFWfk2b9J9Pv7icuOmj+5nDfYwRXNNxHmaFPo/rCaF7DcT23VwagChDvYGl4OFQ2lgHMdKdLejtC0OkA1VVAepMZYZZExZLaULAJ9ARpevG7sSZ9Br17Xxzg3Cv1NReX5MEw52h+I3MtaBPBJ+sBDQSwGUNrE3FIN7JrEhYzWbEkFfyGWbJrstjn1hYHXTzB5ja2EH1rrQUk26UjJlJqJDr9/Oc0oYu3gMxVBZMtsAsfv1Z4f6Lbf3G9YGclkkgr7eHHB/c3qNXIY7qdSuIDyyn/8UeWM3wM0j6xdDLhuQ1gKYgI39we1qrGz2kRt+CSu0PGk1SLdwzrwotruUA44zSJ3Bm+ahjEK2/+pO9LjtXDP+QfwjenuXD8ayFQaFqaZew+Hwh2p+uV4eklgvoU+Q7qGRpd98R9oA/M980UpcppyeEFHDLrKurQu7/e2hYn4aRo2dMLUOI=
  app:
    master: example-accounts
  on:
    repo: ir-taimal10/example-accounts
